### ISSUE TITLE
Output filename does not contain ".fits" extension

### ISSUE THREAD

**Issue by alexanderpiers** [xtachx/SkipperCCDTools#1]
In code usage ./DAMICRecon <Skipper image> Img_01 <begin_frame> <end_frame> gives two output files: Avg_Img_01 and Stdev_Img_01 but they do not have the ".fits" extension. Needed to specifically specify "Img_01.fits" to get it to work.

**Comment by xtachx** [comment]
Fixed w/ 1befdaba5de245845e8b5af4fc8f7507dccc9e54
